spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ECommerce
    username: postgres
    password: "hari@2002"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8600
  servlet:
    context-path: /payments

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

wiremock:
  server:
    port: 8089
    enabled: true