spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ECommerce
    username: postgres
    password: "hari@2002"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  sql:
#    init:
#      mode: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8300
  servlet:
    context-path: /products

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html